# Generated by Django 4.1.4 on 2023-02-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='namw',
            new_name='name',
        ),
    ]
